default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      # Lint files
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # Prevent adding private keys in files
      - id: detect-private-key
      # Detect problemmatic referenced files
      - id: check-symlinks
  # Dockerfile
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: [--ignore, DL3025, --ignore, DL3018]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black