FROM rocker/tidyverse

#########################
ARG IMAGE_VERSION="0.0.1"
#########################

LABEL org.opencontainers.image.title="Quarto-containerized-base"
LABEL version=${IMAGE_VERSION}}
LABEL org.opencontainers.image.version=${IMAGE_VERSION}}
LABEL org.opencontainers.image.authors='Pranav Kumar Mishra'
LABEL description="Using Quarto in an R-Studio Environment via Rocker"
LABEL org.opencontainers.image.source="https://github.com/pranavmishra90/quarto-containerized"
LABEL org.opencontainers.image.licenses="MIT"



RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    wget \
    && rm -rf /var/lib/apt/lists/*

# RUN wget --no-check-certificate -O Mambaforge.sh  https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh


RUN wget --no-check-certificate https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive quarto-linux-amd64.deb

CMD ["bash"]

# The MIT License (MIT)
# Copyright (c) 2022 Pranav Kumar Mishra
