####################################
#         Docker-Compose           #
####################################
version: "3"

####################################
#            Networks              #
####################################

networks:
  # traefik_external:
  #   external:
  #     name: traefik_external
  default:
    driver: bridge

####################################
#            Services              #
####################################

services:
  quarto-r:
    image: rocker/tidyverse
    # build: ./
    container_name: Quarto-R-Studio
    networks: 
      # - traefik_external
      - default
    ports:
      - "3333:3333"
      - "8787:8787"
    volumes:
      - /volume1/Pranav/Research/research-reference:/home/rstudio/research-reference
    environment:
      - PASSWORD=$PASS
    # labels:
    #   - "traefik.enable=true"
    #   # R Studio -------------------------------------------------------------------
    #   ## HTTP Routers
    #   - "traefik.http.routers.quarto-rtr.entrypoints=https"
    #   - "traefik.http.routers.quarto-rtr.tls=true"
    #   - "traefik.http.routers.quarto-rtr.rule=Host(`quarto-r.$DOMAINNAME`)"
    #   ## Middlewares
    #   - "traefik.http.routers.quarto-rtr.middlewares=chain-no-auth@file" #When debugging authelia, use>      # - "traefik.http.routers.quarto-rtr.middlewares=chain-authelia@file"
    #   ## HTTP Services
    #   - "traefik.http.routers.quarto-rtr.service=quarto-svc"
    #   - "traefik.http.services.quarto-svc.loadbalancer.server.port=8787"
      
    #   # Preview-----------------------------------------------------------------

    #   ## HTTP Routers
    #   - "traefik.http.routers.quarto-view.entrypoints=https"
    #   - "traefik.http.routers.quarto-view.tls=true"
    #   - "traefik.http.routers.quarto-view.rule=Host(`quarto-view.$DOMAINNAME`)"
    #   ## Middlewares
    #   - "traefik.http.routers.quarto-view.middlewares=chain-no-auth@file" #When debugging authelia, use>      # - "traefik.http.routers.quarto-view.middlewares=chain-authelia@file"
    #   ## HTTP Services
    #   - "traefik.http.routers.quarto-view.service=quarto-view-svc"
    #   - "traefik.http.services.quarto-view-svc.loadbalancer.server.port=3333"