FROM rocker/tidyverse

#########################
ARG IMAGE_VERSION="0.0.3"
#########################

LABEL org.opencontainers.image.title="Quarto-containerized-base"
LABEL version=${IMAGE_VERSION}}
LABEL org.opencontainers.image.version=${IMAGE_VERSION}}
LABEL org.opencontainers.image.authors='Pranav Kumar Mishra'
LABEL description="The base image for building research documents using Quarto"
LABEL org.opencontainers.image.source="https://github.com/pranavmishra90/quarto-containerized"
LABEL org.opencontainers.image.licenses="MIT"



RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    systemd \
    wget \
    && rm -rf /var/lib/apt/lists/*

## Install Python
RUN wget --no-check-certificate -O /root/Mambaforge.sh  https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
RUN bash /root/Mambaforge.sh -b


## Install Quarto
RUN wget --no-check-certificate -O /root/quarto-linux-amd64.deb https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive /root/quarto-linux-amd64.deb

CMD ["/init"]

# The MIT License (MIT)
# Copyright (c) 2022 Pranav Kumar Mishra
